### ISSUE TITLE
Failed to fetch record for ecspanse_live_dashboard

### ISSUE THREAD

**Issue by mackdunkan** [ketupia/ecspanse_live_dashboard#1]
Hi
Failed to fetch record for ecspanse_live_dashboard from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name ecspanse_live_dashboard (from: mix.exs) in registry

**Comment by ketupia** [comment]
This was a prototype and failed to gain traction.
